[package]
name = "file_monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.28", features = ["derive"] }
ctrlc = "3.4.5"
home = "0.5.11"
tokio = { version = "1.43.0", features = ["full"] }
